"""initial schema

Revision ID: 411db59780c9
Revises: (base)
Create Date: 2026-09-06 10:27:38.907148
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.base  # TZDateTime / BigInt are referenced by the columns below

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_budgets',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('units_used', sa.Float(), nullable=False),
    sa.Column('units_limit', sa.Float(), nullable=False),
    sa.Column('calls', sa.JSON(), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('provider', 'usage_date')
    )
    op.create_table('companies',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('mc_company_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mc_company_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('crawl_days',
    sa.Column('crawl_date', sa.Date(), nullable=False),
    sa.Column('phase', sa.String(length=24), nullable=False),
    sa.Column('new_releases_done', sa.Boolean(), nullable=False),
    sa.Column('new_releases_seen', sa.Integer(), nullable=False),
    sa.Column('browse_page', sa.Integer(), nullable=False),
    sa.Column('browse_offset', sa.Integer(), nullable=False),
    sa.Column('browse_pages_done', sa.Integer(), nullable=False),
    sa.Column('browse_exhausted', sa.Boolean(), nullable=False),
    sa.Column('release_date_watermark', sa.Date(), nullable=True),
    sa.Column('games_claimed', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(), nullable=False),
    sa.CheckConstraint("phase IN ('new_releases', 'browse', 'exhausted')", name='ck_crawl_day_phase'),
    sa.PrimaryKeyConstraint('crawl_date')
    )
    op.create_table('franchises',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('mc_franchise_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mc_franchise_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('job_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ts', app.db.base.TZDateTime(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('crawl_run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index('ix_events_level', ['level', 'id'], unique=False)
        batch_op.create_index('ix_events_run', ['crawl_run_id', 'id'], unique=False)
        batch_op.create_index('ix_events_ts', ['ts'], unique=False)

    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mc_platform_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mc_platform_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('rate_limits',
    sa.Column('bucket_key', sa.String(length=128), nullable=False),
    sa.Column('tokens', sa.Float(), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('bucket_key')
    )
    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('queues', sa.String(length=255), nullable=False),
    sa.Column('started_at', app.db.base.TZDateTime(), nullable=False),
    sa.Column('heartbeat_at', app.db.base.TZDateTime(), nullable=False),
    sa.Column('active_jobs', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('crawl_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('crawl_date', sa.Date(), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('triggered_by', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('phase_at_start', sa.String(length=24), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('source_params', sa.JSON(), nullable=False),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('games_discovered', sa.Integer(), nullable=False),
    sa.Column('games_claimed', sa.Integer(), nullable=False),
    sa.Column('games_skipped_dupe', sa.Integer(), nullable=False),
    sa.Column('games_succeeded', sa.Integer(), nullable=False),
    sa.Column('games_failed', sa.Integer(), nullable=False),
    sa.Column('jobs_enqueued', sa.Integer(), nullable=False),
    sa.Column('started_at', app.db.base.TZDateTime(), nullable=False),
    sa.Column('finished_at', app.db.base.TZDateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_class', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.db.base.TZDateTime(), nullable=False),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'partial', 'failed', 'cancelled')", name='ck_run_status'),
    sa.CheckConstraint("trigger IN ('schedule', 'manual', 'seed', 'reconcile')", name='ck_run_trigger'),
    sa.ForeignKeyConstraint(['crawl_date'], ['crawl_days.crawl_date'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_runs', schema=None) as batch_op:
        batch_op.create_index('ix_runs_by_date', ['crawl_date', 'started_at'], unique=False)
        batch_op.create_index('ix_runs_started', ['started_at'], unique=False)
        batch_op.create_index('uq_crawl_runs_single_active', ['status'], unique=True, sqlite_where=sa.text("status = 'running'"), postgresql_where=sa.text("status = 'running'"))

    op.create_table('games',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('mc_slug', sa.String(length=255), nullable=False),
    sa.Column('mc_title_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('mc_family_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('mc_url', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('title_norm', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=1024), nullable=True),
    sa.Column('card_url', sa.String(length=1024), nullable=True),
    sa.Column('video_url', sa.String(length=1024), nullable=True),
    sa.Column('video_title', sa.String(length=512), nullable=True),
    sa.Column('video_duration_s', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('premiere_year', sa.Integer(), nullable=True),
    sa.Column('esrb_rating', sa.String(length=16), nullable=True),
    sa.Column('must_play', sa.Boolean(), nullable=False),
    sa.Column('franchise_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('lead_platform_id', sa.Integer(), nullable=True),
    sa.Column('lead_metascore', sa.Integer(), nullable=True),
    sa.Column('lead_metascore_count', sa.Integer(), nullable=False),
    sa.Column('lead_userscore', sa.Float(), nullable=True),
    sa.Column('lead_userscore_count', sa.Integer(), nullable=False),
    sa.Column('best_metascore', sa.Integer(), nullable=True),
    sa.Column('best_metascore_count', sa.Integer(), nullable=False),
    sa.Column('best_userscore', sa.Float(), nullable=True),
    sa.Column('best_userscore_count', sa.Integer(), nullable=False),
    sa.Column('platform_count', sa.Integer(), nullable=False),
    sa.Column('critic_reviews_total', sa.Integer(), nullable=False),
    sa.Column('user_reviews_total', sa.Integer(), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('detail_synced_at', app.db.base.TZDateTime(), nullable=True),
    sa.Column('reviews_synced_at', app.db.base.TZDateTime(), nullable=True),
    sa.Column('summaries_synced_at', app.db.base.TZDateTime(), nullable=True),
    sa.Column('youtube_searched_at', app.db.base.TZDateTime(), nullable=True),
    sa.Column('similarity_synced_at', app.db.base.TZDateTime(), nullable=True),
    sa.Column('first_seen_at', app.db.base.TZDateTime(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(), nullable=False),
    sa.CheckConstraint('best_metascore IS NULL OR (best_metascore >= 0 AND best_metascore <= 100)', name='ck_games_best_metascore_range'),
    sa.CheckConstraint('best_userscore IS NULL OR (best_userscore >= 0 AND best_userscore <= 10)', name='ck_games_best_userscore_range'),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_platform_id'], ['platforms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mc_slug'),
    sa.UniqueConstraint('mc_title_id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_mc_family_id'), ['mc_family_id'], unique=False)
        batch_op.create_index('ix_games_reviews_synced', ['reviews_synced_at'], unique=False)
        batch_op.create_index('ix_games_similarity_synced', ['similarity_synced_at'], unique=False)
        batch_op.create_index('ix_games_title_norm', ['title_norm'], unique=False)

    op.create_table('crawl_items',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('crawl_date', sa.Date(), nullable=False),
    sa.Column('game_slug', sa.String(length=255), nullable=False),
    sa.Column('game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('crawl_run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_expires_at', app.db.base.TZDateTime(), nullable=True),
    sa.Column('changed', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('claimed_at', app.db.base.TZDateTime(), nullable=False),
    sa.Column('finished_at', app.db.base.TZDateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'processing', 'done', 'failed', 'skipped')", name='ck_crawl_item_status'),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crawl_date', 'game_slug', name='uq_crawl_items_daily')
    )
    with op.batch_alter_table('crawl_items', schema=None) as batch_op:
        batch_op.create_index('ix_crawl_items_lease', ['lease_expires_at'], unique=False)
        batch_op.create_index('ix_crawl_items_run', ['crawl_run_id', 'status'], unique=False)
        batch_op.create_index('ix_crawl_items_status', ['crawl_date', 'status'], unique=False)

    op.create_table('game_companies',
    sa.Column('game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('company_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.CheckConstraint("role IN ('developer','publisher')", name='ck_game_companies_role'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'company_id', 'role')
    )
    with op.batch_alter_table('game_companies', schema=None) as batch_op:
        batch_op.create_index('ix_game_companies_company', ['company_id', 'role'], unique=False)

    op.create_table('game_genres',
    sa.Column('game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'genre_id')
    )
    with op.batch_alter_table('game_genres', schema=None) as batch_op:
        batch_op.create_index('ix_game_genres_genre', ['genre_id', 'game_id'], unique=False)

    op.create_table('game_platforms',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('mc_related_game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_lead', sa.Boolean(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('metascore_raw', sa.Integer(), nullable=True),
    sa.Column('metascore_count', sa.Integer(), nullable=False),
    sa.Column('metascore_positive', sa.Integer(), nullable=False),
    sa.Column('metascore_neutral', sa.Integer(), nullable=False),
    sa.Column('metascore_negative', sa.Integer(), nullable=False),
    sa.Column('critic_sentiment', sa.String(length=64), nullable=True),
    sa.Column('userscore_raw', sa.Float(), nullable=True),
    sa.Column('userscore_count', sa.Integer(), nullable=False),
    sa.Column('userscore_positive', sa.Integer(), nullable=False),
    sa.Column('userscore_neutral', sa.Integer(), nullable=False),
    sa.Column('userscore_negative', sa.Integer(), nullable=False),
    sa.Column('user_sentiment', sa.String(length=64), nullable=True),
    sa.Column('critic_reviews_with_text', sa.Integer(), nullable=False),
    sa.Column('user_reviews_with_text', sa.Integer(), nullable=False),
    sa.Column('critic_reviews_synced_at', app.db.base.TZDateTime(), nullable=True),
    sa.Column('user_reviews_synced_at', app.db.base.TZDateTime(), nullable=True),
    sa.Column('created_at', app.db.base.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(), nullable=False),
    sa.CheckConstraint('metascore_raw IS NULL OR (metascore_raw >= 0 AND metascore_raw <= 100)', name='ck_gp_metascore_range'),
    sa.CheckConstraint('userscore_raw IS NULL OR (userscore_raw >= 0 AND userscore_raw <= 10)', name='ck_gp_userscore_range'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'platform_id', name='uq_game_platforms')
    )
    with op.batch_alter_table('game_platforms', schema=None) as batch_op:
        batch_op.create_index('ix_gp_game', ['game_id'], unique=False)
        batch_op.create_index('ix_gp_platform_game', ['platform_id', 'game_id'], unique=False)
        batch_op.create_index('uq_game_platforms_one_lead', ['game_id'], unique=True, sqlite_where=sa.text("is_lead"), postgresql_where=sa.text("is_lead"))

    op.create_table('jobs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('queue', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('crawl_run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('parent_job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', app.db.base.TZDateTime(), nullable=True),
    sa.Column('lease_expires_at', app.db.base.TZDateTime(), nullable=True),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('error_class', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('queued_at', app.db.base.TZDateTime(), nullable=False),
    sa.Column('started_at', app.db.base.TZDateTime(), nullable=True),
    sa.Column('finished_at', app.db.base.TZDateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed', 'retrying', 'dead', 'skipped')", name='ck_job_status'),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_jobs_idempotency')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_by_game', ['game_id', 'job_type', 'finished_at'], unique=False)
        batch_op.create_index('ix_jobs_claimable', ['status', 'queue', 'priority', 'queued_at'], unique=False)
        batch_op.create_index('ix_jobs_lease', ['lease_expires_at'], unique=False)
        batch_op.create_index('ix_jobs_recent', ['queued_at'], unique=False)

    op.create_table('similar_games',
    sa.Column('game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('similar_game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('computed_at', app.db.base.TZDateTime(), nullable=False),
    sa.CheckConstraint("method IN ('metadata', 'hybrid')", name='ck_similar_method'),
    sa.CheckConstraint('game_id <> similar_game_id', name='ck_similar_not_self'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['similar_game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'similar_game_id')
    )
    with op.batch_alter_table('similar_games', schema=None) as batch_op:
        batch_op.create_index('ix_similar_lookup', ['game_id', 'rank'], unique=False)
        batch_op.create_index('ix_similar_reverse', ['similar_game_id'], unique=False)

    op.create_table('youtube_videos',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=True),
    sa.Column('channel_title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('like_count', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('published_at', app.db.base.TZDateTime(), nullable=True),
    sa.Column('has_captions', sa.Boolean(), nullable=True),
    sa.Column('default_audio_language', sa.String(length=16), nullable=True),
    sa.Column('live_broadcast', sa.String(length=16), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('rank_score', sa.Float(), nullable=True),
    sa.Column('rank_components', sa.JSON(), nullable=False),
    sa.Column('rejected_reason', sa.String(length=64), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('discovery_source', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'video_id', name='uq_youtube_video')
    )
    with op.batch_alter_table('youtube_videos', schema=None) as batch_op:
        batch_op.create_index('ix_youtube_rank', ['game_id', 'rank_score'], unique=False)
        batch_op.create_index('uq_youtube_one_selected', ['game_id'], unique=True, sqlite_where=sa.text("is_selected"), postgresql_where=sa.text("is_selected"))

    op.create_table('review_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('game_platform_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('ordering_version', sa.Integer(), nullable=False),
    sa.Column('sampling_version', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.JSON(), nullable=False),
    sa.Column('date_min', sa.Date(), nullable=True),
    sa.Column('date_max', sa.Date(), nullable=True),
    sa.Column('built_at', app.db.base.TZDateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('critic', 'user')", name='ck_snapshot_kind'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_platform_id'], ['game_platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_platform_id', 'kind', 'content_hash', name='uq_snapshot_content')
    )
    with op.batch_alter_table('review_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshot_gp_kind_built', ['game_platform_id', 'kind', 'built_at'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('game_platform_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source_review_id', sa.String(length=64), nullable=True),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('publication_name', sa.String(length=255), nullable=True),
    sa.Column('publication_slug', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_max', sa.Integer(), nullable=False),
    sa.Column('score_normalized', sa.Float(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('language_hint', sa.String(length=8), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('is_spoiler', sa.Boolean(), nullable=False),
    sa.Column('source_version', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('thumbs_up', sa.Integer(), nullable=True),
    sa.Column('thumbs_down', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', app.db.base.TZDateTime(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('critic', 'user')", name='ck_reviews_kind'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_platform_id'], ['game_platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_platform_id', 'kind', 'dedupe_key', name='uq_reviews_dedupe')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('ix_reviews_game_kind_date', ['game_id', 'kind', 'published_on', 'id'], unique=False)
        batch_op.create_index('ix_reviews_gp_kind', ['game_platform_id', 'kind'], unique=False)

    op.create_table('youtube_transcripts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('video_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('is_auto_generated', sa.Boolean(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fetched_at', app.db.base.TZDateTime(), nullable=True),
    sa.Column('created_at', app.db.base.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'available', 'unavailable', 'failed')", name='ck_transcript_status'),
    sa.ForeignKeyConstraint(['video_id'], ['youtube_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('gap_explanations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('game_platform_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('critic_snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('user_snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('gap_points', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('generated_at', app.db.base.TZDateTime(), nullable=False),
    sa.CheckConstraint("status IN ('fresh', 'skipped_no_data', 'rejected', 'failed')", name='ck_gap_status'),
    sa.ForeignKeyConstraint(['critic_snapshot_id'], ['review_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_platform_id'], ['game_platforms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_snapshot_id'], ['review_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_platform_id', 'critic_snapshot_id', 'user_snapshot_id', name='uq_gap_snapshots')
    )
    with op.batch_alter_table('gap_explanations', schema=None) as batch_op:
        batch_op.create_index('uq_gap_current', ['game_platform_id'], unique=True, sqlite_where=sa.text("is_current"), postgresql_where=sa.text("is_current"))

    op.create_table('snapshot_reviews',
    sa.Column('snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('evidence_ref', sa.String(length=8), nullable=False),
    sa.Column('review_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['review_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'evidence_ref'),
    sa.UniqueConstraint('snapshot_id', 'review_id', name='uq_snapshot_review')
    )
    with op.batch_alter_table('snapshot_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_snapshot_reviews_position', ['snapshot_id', 'position'], unique=False)

    op.create_table('summaries',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('game_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('game_platform_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('audience', sa.String(length=16), nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('overall', sa.Text(), nullable=True),
    sa.Column('aspect_verdicts', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('reviews_used', sa.Integer(), nullable=False),
    sa.Column('reviews_candidates', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(length=32), nullable=True),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('params_version', sa.String(length=32), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('generated_at', app.db.base.TZDateTime(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(), nullable=False),
    sa.CheckConstraint("audience IN ('critic', 'user', 'letsplay')", name='ck_summary_audience'),
    sa.CheckConstraint("status IN ('fresh', 'skipped_no_data', 'rejected', 'failed')", name='ck_summary_status'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_platform_id'], ['game_platforms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['review_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_platform_id', 'audience', 'input_fingerprint', name='uq_summary_fingerprint')
    )
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.create_index('ix_summaries_history', ['game_platform_id', 'audience', 'version'], unique=False)
        batch_op.create_index('uq_summaries_current', ['game_platform_id', 'audience'], unique=True, sqlite_where=sa.text("is_current"), postgresql_where=sa.text("is_current"))

    op.create_table('summary_claims',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('summary_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('aspect', sa.String(length=32), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=16), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('strength', sa.String(length=16), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('validation', sa.String(length=48), nullable=False),
    sa.Column('validation_detail', sa.Text(), nullable=True),
    sa.CheckConstraint("aspect IN ('gameplay', 'graphics', 'story', 'mechanics', 'performance', 'sound_music', 'innovation', 'replayability', 'content_amount', 'difficulty', 'ui_ux', 'price_value', 'bugs', 'multiplayer', 'other')", name='ck_claim_aspect'),
    sa.CheckConstraint("claim_type IN ('descriptive', 'comparative', 'temporal')", name='ck_claim_type'),
    sa.CheckConstraint("side IN ('positive', 'negative')", name='ck_claim_side'),
    sa.CheckConstraint("validation IN ('accepted', 'rejected_missing_ref', 'rejected_low_support', 'rejected_vague', 'rejected_temporal_unsupported', 'rejected_quote_not_found', 'rejected_aspect_unsupported')", name='ck_claim_validation'),
    sa.ForeignKeyConstraint(['summary_id'], ['summaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('summary_claims', schema=None) as batch_op:
        batch_op.create_index('ix_claims_summary', ['summary_id', 'side', 'position'], unique=False)
        batch_op.create_index('ix_claims_validation', ['validation'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary_claims', schema=None) as batch_op:
        batch_op.drop_index('ix_claims_validation')
        batch_op.drop_index('ix_claims_summary')

    op.drop_table('summary_claims')
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_index('uq_summaries_current', sqlite_where=sa.text("is_current"), postgresql_where=sa.text("is_current"))
        batch_op.drop_index('ix_summaries_history')

    op.drop_table('summaries')
    with op.batch_alter_table('snapshot_reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_reviews_position')

    op.drop_table('snapshot_reviews')
    with op.batch_alter_table('gap_explanations', schema=None) as batch_op:
        batch_op.drop_index('uq_gap_current', sqlite_where=sa.text("is_current"), postgresql_where=sa.text("is_current"))

    op.drop_table('gap_explanations')
    op.drop_table('youtube_transcripts')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_gp_kind')
        batch_op.drop_index('ix_reviews_game_kind_date')

    op.drop_table('reviews')
    with op.batch_alter_table('review_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_gp_kind_built')

    op.drop_table('review_snapshots')
    with op.batch_alter_table('youtube_videos', schema=None) as batch_op:
        batch_op.drop_index('uq_youtube_one_selected', sqlite_where=sa.text("is_selected"), postgresql_where=sa.text("is_selected"))
        batch_op.drop_index('ix_youtube_rank')

    op.drop_table('youtube_videos')
    with op.batch_alter_table('similar_games', schema=None) as batch_op:
        batch_op.drop_index('ix_similar_reverse')
        batch_op.drop_index('ix_similar_lookup')

    op.drop_table('similar_games')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_recent')
        batch_op.drop_index('ix_jobs_lease')
        batch_op.drop_index('ix_jobs_claimable')
        batch_op.drop_index('ix_jobs_by_game')

    op.drop_table('jobs')
    with op.batch_alter_table('game_platforms', schema=None) as batch_op:
        batch_op.drop_index('uq_game_platforms_one_lead', sqlite_where=sa.text("is_lead"), postgresql_where=sa.text("is_lead"))
        batch_op.drop_index('ix_gp_platform_game')
        batch_op.drop_index('ix_gp_game')

    op.drop_table('game_platforms')
    with op.batch_alter_table('game_genres', schema=None) as batch_op:
        batch_op.drop_index('ix_game_genres_genre')

    op.drop_table('game_genres')
    with op.batch_alter_table('game_companies', schema=None) as batch_op:
        batch_op.drop_index('ix_game_companies_company')

    op.drop_table('game_companies')
    with op.batch_alter_table('crawl_items', schema=None) as batch_op:
        batch_op.drop_index('ix_crawl_items_status')
        batch_op.drop_index('ix_crawl_items_run')
        batch_op.drop_index('ix_crawl_items_lease')

    op.drop_table('crawl_items')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index('ix_games_title_norm')
        batch_op.drop_index('ix_games_similarity_synced')
        batch_op.drop_index('ix_games_reviews_synced')
        batch_op.drop_index(batch_op.f('ix_games_mc_family_id'))

    op.drop_table('games')
    with op.batch_alter_table('crawl_runs', schema=None) as batch_op:
        batch_op.drop_index('uq_crawl_runs_single_active', sqlite_where=sa.text("status = 'running'"), postgresql_where=sa.text("status = 'running'"))
        batch_op.drop_index('ix_runs_started')
        batch_op.drop_index('ix_runs_by_date')

    op.drop_table('crawl_runs')
    op.drop_table('worker_heartbeats')
    op.drop_table('rate_limits')
    op.drop_table('platforms')
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_ts')
        batch_op.drop_index('ix_events_run')
        batch_op.drop_index('ix_events_level')

    op.drop_table('job_events')
    op.drop_table('genres')
    op.drop_table('franchises')
    op.drop_table('crawl_days')
    op.drop_table('companies')
    op.drop_table('api_budgets')
    # ### end Alembic commands ###
